# System of Linear Equations with a Unique Solution, Matrix Inverse and the Determinant

The goal of this homework is to learn how to solve systems of linear equations and to be able to compute the determinant and the inverse of an invertible matrix.

**After this assignment you will be able to:**
- Use `NumPy` package to set up the arrays corresponding to the system of linear equations.
- Evaluate the determinant of a matrix and find the solution of the system with `NumPy` linear algebra package.
- Perform row reduction to bring matrix into row echelon form
- Find the solution for the system of linear equations using row reduced approach.
- Compute the inverse of a matrix with `Numpy` linear algebra package and using row reduction approach.

## 1. Solving System of Linear Equations

### 1.1 Row Reduction approach

Solve the following system of linear equations using the reduction method (as mentioned in the week 2 lab):
$$\begin{cases}
x + 2y - 3z + 4w = 12, \\ 2x + 2y - 2z + 3w = 10, \\ y + z = -1, \\ x - y + z - 2w = -4 \end{cases}\tag{1}$$


In [1]:
import numpy as np

### 1.2 `Numpy` linear algebra package
Solve the above system of linear equations using the `numpy.linalg` package.

In [3]:
A = np.array([
    [1, 2, -3, 4],
    [2, 2, -2, 3],
    [0, 1, 1, 0],
    [1, -1, 1, -2]
])

b = np.array([12, 10, -1, -4])

print(np.linalg.solve(A, b))

[ 1. -0. -1.  2.]


## 2. Determinant
### 2.1 Compute the determinant of matrix $A$ using the `numpy.linalg` package:

$$ \begin{align}
  \textbf{A}  = \begin{bmatrix}
1 & 0 & -2\\
3 & 1 & -2\\
-5 & -1 & 9
\end{bmatrix}
  \end{align}
  $$

In [5]:
A = np.array([
    [1, 0, -2],
    [3, 1, -2],
    [-5, -1, 9]
])
print(np.linalg.det(A))

3.000000000000001


### 2.2 Is the above matrix invertible? Why?

The above matrix is invertible because the determinate is not 0.  If the determinate was zero it would be singluar.

# 3. Matrix Inverse
### 3.1 Compute the inverse of non-singular matrix $B$ using row reduction
$$ \begin{align}
  \textbf{B}  = \begin{bmatrix}
1 & 2 & 1\\
4 & 4 & 5\\
6 & 7 & 7
\end{bmatrix}
  \end{align}
  $$

In [10]:
def MultiplyRow(M, row, scalar):
    M_new = M.copy()
    M_new[row] = M_new[row] * scalar
    return M_new

def AddRows(M, row_num_1, row_num_2, scalar):
    M_new = M.copy()
    M_new[row_num_2] = scalar * M_new[row_num_1] + M_new[row_num_2]
    return M_new

def ExchangeRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

In [44]:
B = np.array([
    [1, 2, 1],
    [4, 4, 5],
    [6, 7, 7]
], dtype=np.dtype(float))

B_system = np.hstack((B, np.eye(3,3))); print(B_system)
B_system = AddRows(B_system, 0, 1, -4); print(B_system)
B_system = AddRows(B_system, 0, 2, -6); print(B_system)
B_system = MultiplyRow(B_system, 1, -1/4); print(B_system)
B_system = AddRows(B_system, 1, 2, 5); print(B_system)
B_system = MultiplyRow(B_system, 2, -4); print(B_system)
B_system = AddRows(B_system, 2, 1, .25); print(B_system)
B_system = AddRows(B_system, 2, 0, -1); print(B_system)
B_system = AddRows(B_system, 1, 0, -2); print(B_system)

[[1. 2. 1. 1. 0. 0.]
 [4. 4. 5. 0. 1. 0.]
 [6. 7. 7. 0. 0. 1.]]
[[ 1.  2.  1.  1.  0.  0.]
 [ 0. -4.  1. -4.  1.  0.]
 [ 6.  7.  7.  0.  0.  1.]]
[[ 1.  2.  1.  1.  0.  0.]
 [ 0. -4.  1. -4.  1.  0.]
 [ 0. -5.  1. -6.  0.  1.]]
[[ 1.    2.    1.    1.    0.    0.  ]
 [-0.    1.   -0.25  1.   -0.25 -0.  ]
 [ 0.   -5.    1.   -6.    0.    1.  ]]
[[ 1.    2.    1.    1.    0.    0.  ]
 [-0.    1.   -0.25  1.   -0.25 -0.  ]
 [ 0.    0.   -0.25 -1.   -1.25  1.  ]]
[[ 1.    2.    1.    1.    0.    0.  ]
 [-0.    1.   -0.25  1.   -0.25 -0.  ]
 [-0.   -0.    1.    4.    5.   -4.  ]]
[[ 1.  2.  1.  1.  0.  0.]
 [-0.  1.  0.  2.  1. -1.]
 [-0. -0.  1.  4.  5. -4.]]
[[ 1.  2.  0. -3. -5.  4.]
 [-0.  1.  0.  2.  1. -1.]
 [-0. -0.  1.  4.  5. -4.]]
[[ 1.  0.  0. -7. -7.  6.]
 [-0.  1.  0.  2.  1. -1.]
 [-0. -0.  1.  4.  5. -4.]]


In [47]:
# extract inverse from computed matrix
B_inv = B_system[:, -3:]; print(B_inv)

[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]


In [ ]:
# Test if B*B_inv = I
B.dot(B_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 3.2 Compute the inverse matrix $B$ using the `numpy.linalg` package.

In [46]:
print(np.linalg.inv(B))

[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]
