# Solving System of Linear Equations with 3 variables



In this lab we will:

- Use `NumPy` linear algebra package to solve a system of linear equations
- Perform row transformation operations to bring a matrix into row echelon form
- Find the solution for the system of linear equations using the row echolon form of the matrix

## Packages

Load the `NumPy` *library* into memory

In [1]:
import numpy as np

<a name='1'></a>
## 1 - Representing and Solving a System of Linear Equations using Matrices

<a name='1.1'></a>
### 1.1 - System of Linear Equations

Here is a **system of linear equations** with three equations and three unknown variables:


$$\begin{cases}
x+\ \ y+3z=15 \\ x + 2y + 4z = 21 \\ x + \ \ y+ 2z = 13 \end{cases}\tag{1}$$

**To solve** this system of linear equations means to find values of $x$, $y$, $z$ that satisfy all of its equations simultaneously.

<a name='1.2'></a>
### 1.2 - Solving Systems of Linear Equations using Matrices

Create a a 2-D numpy array $A$ which will be a matrix where each row will represent one equation in the system, and $b$ which must be a 1-D array of the right side coefficients:

In [2]:
A = np.array([
    [1, 1, 3],
    [1, 2, 4],
    [1, 1, 2]
], dtype=np.dtype(float))
b = np.array([15, 21, 13])


Print the dimentions of $A$ and $b$ using `shape()` method of `NumPy`.



In [3]:
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of b: {np.shape(b)}")

Shape of A: (3, 3)
Shape of b: (3,)


Solve the equaiton $Ax=b$ using `np.linalg.solve(A, b)`. The result will be saved in the 1-D array $s$. The elements will correspond to the values of $x$, $y$ and $z$:

In [4]:
s = np.linalg.solve(A, b)

print(f"Solution: {s}")

Solution: [5. 4. 2.]


<a name='2'></a>
## 2 - Solving System of Linear Equations using Row Reduction

<a name='2.1'></a>
### 2.1 - Preparation for Row Reduction


Firstly, we need to create an augmented matrix $A$_$system$  by unify  matrix $A$ and array $b$ into one matrix using the `np.hstack()` function.


In [5]:
A_system = np.hstack((A, b.reshape((3,1))))
print(A_system)


[[ 1.  1.  3. 15.]
 [ 1.  2.  4. 21.]
 [ 1.  1.  2. 13.]]


<a name='2.2'></a>

### 2.2 - Elementary Row Operations
While solving a system of linear equations, we are allowed to performed these row transformation operations:

1.   Multiply one row by a non-zero number
2.   Replace one row with the sum of that row with another row.
3.   Exchange two rows.


Next, we will define one Python function for each of the operations mentioned above:

In [6]:
#row = scalar * row
def MultiplyRow(M, row, scalar):
    M_new = M.copy()
    M_new[row] = M_new[row] * scalar
    return M_new

In [7]:
def AddRows(M, row_num_1, row_num_2, scalar):
    M_new = M.copy()
    M_new[row_num_2] = scalar * M_new[row_num_1] + M_new[row_num_2]
    return M_new

In [8]:
def ExchangeRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

In [9]:
# exchange row_num_1 and row_num_2 of the matrix M
def ExchangeRows(M, row_num_1, row_num_2):
    M_copy = M.copy()

    # Make a copy of Row 1
    tmp_row_1 = M_copy[row_num_1].copy()
    tmp_row_2 = M_copy[row_num_2].copy()

    M_copy[row_num_1] = tmp_row_2
    M_copy[row_num_2] = tmp_row_1

    return M_copy

<a name='2.3'></a>


### 2.3 - Row Echelon Form
Provide all steps to convert Matrix $A$_$system$ into row echelon form.

- Row_2 = Row_2 - Row_1

In [10]:
print(A_system)
A_ref = AddRows(A_system, 0, 1, -1)
print(A_ref)

[[ 1.  1.  3. 15.]
 [ 1.  2.  4. 21.]
 [ 1.  1.  2. 13.]]
[[ 1.  1.  3. 15.]
 [ 0.  1.  1.  6.]
 [ 1.  1.  2. 13.]]


- Row_3  = Row_3 - Row_1

In [11]:
A_ref = AddRows(A_ref, 0, 2, -1)
print(A_ref)

[[ 1.  1.  3. 15.]
 [ 0.  1.  1.  6.]
 [ 0.  0. -1. -2.]]


- Row_3 = -1 * Row_3

In [12]:
A_ref = MultiplyRow(A_ref, 2, -1)
print(A_ref)

[[ 1.  1.  3. 15.]
 [ 0.  1.  1.  6.]
 [-0. -0.  1.  2.]]


Now, it is easy to find the value of z is 2 from the third row. Moving upward by substritution we can find teh value of y is 4 and value of x is 5.  


In [13]:
z = 2.0
y = (A_ref[1,3] - A_ref[1,2] * z) / A_ref[1,1]
x = (A_ref[0,3] - A_ref[0,2] * z - A_ref[0,1] * y) / A_ref[0,0]

print(x, y, z)

5.0 4.0 2.0


<a name='2.4'></a>


### 2.4 - Reduced Row Echelon Form

Let us continue our row operations to convert the matrix into reduced row echelon form.

- Row_2  = Row_2 - Row_3

In [14]:
A_rref = AddRows(A_ref, 2, 1, -1)
print(A_rref)

[[ 1.  1.  3. 15.]
 [ 0.  1.  0.  4.]
 [-0. -0.  1.  2.]]


Row_1 = Row_1 - 3*Row_3

In [ ]:
A_rref = AddRows(A_rref,2,0, -3)
print(A_rref)

[[ 1.  1.  0.  9.]
 [ 0.  1.  0.  4.]
 [-0. -0.  1.  2.]]


Row_1 = Row_1 - Row_2

In [16]:
A_rref = AddRows(A_rref, 1, 0, -1)
print(A_rref)

[[ 1.  0.  0.  5.]
 [ 0.  1.  0.  4.]
 [-0. -0.  1.  2.]]


Once, the matrix has reached reduced row echelon form, it is trivial to see that: \\
$$x = 5 \\
y = 4 \\
z=2$$

In [19]:
x = A_rref[0][-1]
y = A_rref[1][-1]
z = A_rref[2][-1]

<a name='3'></a>
## 3 - Computing the inverse of matrices using Row Reduction

In [21]:
print("Matrix A: ")
print(A)

Matrix A: 
[[1. 1. 3.]
 [1. 2. 4.]
 [1. 1. 2.]]


In [22]:
det = np.linalg.det(A)
print(f"Determinant of A: {det}")

Determinant of A: -1.0


Firstly, we need to create an augmented matrix by unifying matrix A with a 3x3 identity matrix using using the `np.hstack()` function.

In [25]:
A_aug = np.hstack((A, np.eye(3,3)))
print("The augmented matrix is: ")
print(A_aug)

The augmented matrix is: 
[[1. 1. 3. 1. 0. 0.]
 [1. 2. 4. 0. 1. 0.]
 [1. 1. 2. 0. 0. 1.]]


Apply all row transformations to convert the left 3 by 3 matrix to the identity matrix.

In [28]:
A_ref = AddRows(A_aug, 0, 1, -1); print(A_ref)
A_ref = AddRows(A_ref, 0, 2, -1); print(A_ref)
A_ref = MultiplyRow(A_ref, 2, -1); print(A_ref)
A_ref = AddRows(A_ref, 2, 1, -1); print(A_ref)
A_ref = AddRows(A_ref,2,0, -3); print(A_ref)
A_ref = AddRows(A_ref, 1, 0, -1); print(A_ref)

[[ 1.  1.  3.  1.  0.  0.]
 [ 0.  1.  1. -1.  1.  0.]
 [ 1.  1.  2.  0.  0.  1.]]
[[ 1.  1.  3.  1.  0.  0.]
 [ 0.  1.  1. -1.  1.  0.]
 [ 0.  0. -1. -1.  0.  1.]]
[[ 1.  1.  3.  1.  0.  0.]
 [ 0.  1.  1. -1.  1.  0.]
 [-0. -0.  1.  1. -0. -1.]]
[[ 1.  1.  3.  1.  0.  0.]
 [ 0.  1.  0. -2.  1.  1.]
 [-0. -0.  1.  1. -0. -1.]]
[[ 1.  1.  0. -2.  0.  3.]
 [ 0.  1.  0. -2.  1.  1.]
 [-0. -0.  1.  1. -0. -1.]]
[[ 1.  0.  0.  0. -1.  2.]
 [ 0.  1.  0. -2.  1.  1.]
 [-0. -0.  1.  1. -0. -1.]]


In [30]:
A_ref

array([[ 1.,  0.,  0.,  0., -1.,  2.],
       [ 0.,  1.,  0., -2.,  1.,  1.],
       [-0., -0.,  1.,  1., -0., -1.]])

In [33]:
A_inv = A_ref[:,-3:]

In [34]:
A_inv

array([[ 0., -1.,  2.],
       [-2.,  1.,  1.],
       [ 1., -0., -1.]])

Make sure to check whether A time A_inv gives the identity matrix:

In [35]:
A.dot(A_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

There is an easier way to compute the inverse of a matrix by using `np.linalg.inv` function.

In [36]:
print(np.linalg.inv(A))

[[ 0. -1.  2.]
 [-2.  1.  1.]
 [ 1. -0. -1.]]
